---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-http
  labels:
    app: go-hello-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hello-http
  template:
    metadata:
      labels:
        app: go-hello-http
        backstage.io/kubernetes-id: go-hello-http
    spec:
      containers:
        - name: go-hello-http
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi
          ports:
            - containerPort: 8080
